import type { Metadata } from "next";

import "./globals.css";

import ReduxProvider from "@/redux/providers/ReduxProvider";

import AuthModal from "@/components/AuthModal/AuthModal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        <ReduxProvider>
          {children}
          <AuthModal />
        </ReduxProvider>
      </body>
    </html>
  );
}
