import type { Metadata } from "next";

import "./globals.css";

import ReduxProvider from "@/redux/providers/ReduxProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        <ReduxProvider>
          {children}
          {modal}
        </ReduxProvider>
      </body>
    </html>
  );
}
