import type { Metadata } from "next";

import "./globals.css";

import ReduxProvider from "@/redux/providers/ReduxProvider";
import ThemeWrapper from "@/components/ThemeWrapper/ThemeWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <ThemeWrapper>
          {children}
          {modal}
        </ThemeWrapper>
      </ReduxProvider>
    </html>
  );
}
